"Steam/Cached/PurchaseSubBillingInfoReview.res"
{
	"InfoLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"InfoLabel"
		"xpos"		"24"
		"ypos"		"22"
		"wide"		"360"
		"tall"		"36"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Steam_SubscribeReviewInfo"
		"textAlignment"		"north-west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label2"
	{
		"ControlName"		"Label"
		"fieldName"		"Label2"
		"xpos"		"48"
		"ypos"		"62"
		"wide"		"108"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Name"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label3"
	{
		"ControlName"		"Label"
		"fieldName"		"Label3"
		"xpos"		"48"
		"ypos"		"80"
		"wide"		"108"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Credit card type"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label4"
	{
		"ControlName"		"Label"
		"fieldName"		"Label4"
		"xpos"		"48"
		"ypos"		"98"
		"wide"		"108"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Account Number"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label5"
	{
		"ControlName"		"Label"
		"fieldName"		"Label5"
		"xpos"		"48"
		"ypos"		"116"
		"wide"		"108"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Expiration"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label6"
	{
		"ControlName"		"Label"
		"fieldName"		"Label6"
		"xpos"		"48"
		"ypos"		"134"
		"wide"		"108"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Street address"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label7"
	{
		"ControlName"		"Label"
		"fieldName"		"Label7"
		"xpos"		"48"
		"ypos"		"152"
		"wide"		"108"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"City"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label8"
	{
		"ControlName"		"Label"
		"fieldName"		"Label8"
		"xpos"		"48"
		"ypos"		"170"
		"wide"		"108"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Postcode"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label9"
	{
		"ControlName"		"Label"
		"fieldName"		"Label9"
		"xpos"		"48"
		"ypos"		"188"
		"wide"		"108"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"State"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Label10"
	{
		"ControlName"		"Label"
		"fieldName"		"Label10"
		"xpos"		"48"
		"ypos"		"206"
		"wide"		"108"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"Country"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"LabelCost"
	{
		"ControlName"		"Label"
		"fieldName"		"LabelCost"
		"xpos"		"48"
		"ypos"		"244"
		"wide"		"108"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Steam_ProductCostLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"LabelTax"
	{
		"ControlName"		"Label"
		"fieldName"		"LabelTax"
		"xpos"		"48"
		"ypos"		"262"
		"wide"		"108"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Steam_TaxLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"LabelTotal"
	{
		"ControlName"		"Label"
		"fieldName"		"LabelTotal"
		"xpos"		"48"
		"ypos"		"280"
		"wide"		"108"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"#Steam_TotalLabel"
		"textAlignment"		"west"
		"dulltext"		"1"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Data2"
	{
		"ControlName"		"Label"
		"fieldName"		"Data2"
		"xpos"		"166"
		"ypos"		"62"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"g c"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Data3"
	{
		"ControlName"		"Label"
		"fieldName"		"Data3"
		"xpos"		"166"
		"ypos"		"80"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"MasterCard"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Data4"
	{
		"ControlName"		"Label"
		"fieldName"		"Data4"
		"xpos"		"166"
		"ypos"		"98"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"5123456789010001"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Data5"
	{
		"ControlName"		"Label"
		"fieldName"		"Data5"
		"xpos"		"166"
		"ypos"		"116"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"01/2004"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Data6"
	{
		"ControlName"		"Label"
		"fieldName"		"Data6"
		"xpos"		"166"
		"ypos"		"134"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"123"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Data7"
	{
		"ControlName"		"Label"
		"fieldName"		"Data7"
		"xpos"		"166"
		"ypos"		"152"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"123"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Data8"
	{
		"ControlName"		"Label"
		"fieldName"		"Data8"
		"xpos"		"166"
		"ypos"		"170"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"12345"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Data9"
	{
		"ControlName"		"Label"
		"fieldName"		"Data9"
		"xpos"		"166"
		"ypos"		"188"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"wa"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"Data10"
	{
		"ControlName"		"Label"
		"fieldName"		"Data10"
		"xpos"		"166"
		"ypos"		"206"
		"wide"		"192"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"United States"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"DataCost"
	{
		"ControlName"		"Label"
		"fieldName"		"DataCost"
		"xpos"		"150"
		"ypos"		"244"
		"wide"		"56"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"$29.95"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"DataTax"
	{
		"ControlName"		"Label"
		"fieldName"		"DataTax"
		"xpos"		"150"
		"ypos"		"262"
		"wide"		"56"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"2.63"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
	"DataTotal"
	{
		"ControlName"		"Label"
		"fieldName"		"DataTotal"
		"xpos"		"150"
		"ypos"		"280"
		"wide"		"56"
		"tall"		"16"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"$32.58"
		"textAlignment"		"east"
		"dulltext"		"0"
		"brighttext"		"1"
		"wrap"		"0"
	}
	"Divider1"
	{
		"ControlName"		"Divider"
		"fieldName"		"Divider1"
		"xpos"		"24"
		"ypos"		"232"
		"wide"		"340"
		"tall"		"2"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"1"
		"enabled"		"1"
		"tabPosition"		"0"
	}
	"Label1"
	{
		"ControlName"		"Label"
		"fieldName"		"Label1"
		"xpos"		"223"
		"ypos"		"279"
		"wide"		"160"
		"tall"		"18"
		"autoResize"		"0"
		"pinCorner"		"0"
		"visible"		"0"
		"enabled"		"1"
		"tabPosition"		"0"
		"labelText"		"(Exchange rate calculator)"
		"textAlignment"		"west"
		"dulltext"		"0"
		"brighttext"		"0"
		"wrap"		"0"
	}
}
 